spring:
  mail:
    host: 
    port: 
    username: 
    password: 
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rabbit:
  queue: EMAIL_SENDING_TASKS
  exchange: exchange
  routing-key: TaskTrackerKey

sender:
  address: 
